services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # NODE_ENV: production
      PAYLOAD_DATABASE_URI: postgres://postgres:123456@database:5432/postgres
      PAYLOAD_SECRET: XXXX
    restart: always
